## ebs.ErrorBudget.run_etc Required Arguments
### Fixed:  
* output_dir  
* ref_json_filename  
* pp_json_filename  
* contrast_filename  
* target_list  
* luminosity  
* eeid  
* eepsr  
* npoints 

### Non-variable, mutable  
### Possibly variable  
* exo_zodi  
* wfe
* wfsc_factor
* sensitivity
* output_filename_prefix
* var_par
* *args  

In [1]:
import inspect
import yaml
import numpy as np
import ebs.ebs as ebs
import utilities.log_pdf as pdf

In [2]:
args_print = inspect.getfullargspec(ebs.ErrorBudget)[0]
print(
    f"ebs class arguments:\n{args_print}\n"
    )
args_print = inspect.getfullargspec(ebs.ErrorBudget.run_etc)[0]
print(
    f"ebs.run_etc method arguments:\n{args_print}"
      )

ebs class arguments:
['self', 'input_dir', 'output_dir', 'ref_json_filename', 'pp_json_filename', 'contrast_filename', 'target_list', 'luminosity', 'eeid', 'eepsr', 'exo_zodi', 'npoints']

ebs.run_etc method arguments:
['self', 'wfe', 'wfsc_factor', 'sensitivity', 'output_filename_prefix', 'var_par']


In [3]:
pdf.uniform

<function utilities.log_pdf.uniform(x, lower_bound, upper_bound)>

In [4]:
with open('mcmc.yml', 'r') as config:
    config = yaml.load(config, Loader=yaml.FullLoader)

In [5]:
# config

In [6]:
print(
    np.array(config['mcmc']['prior_args']
             [config['mcmc']['variable_id'][0]][0]))

[[9.9999e-07 9.9999e-07 9.9999e-07 9.9999e-07]
 [9.999e-05 9.999e-05 9.999e-05 9.999e-05]
 [0.00990099 0.00990099 0.00990099 0.00990099]
 [None None None None]
 [None None None None]]


In [7]:
print(
    np.array(config['mcmc']['prior_args']
             [config['mcmc']['variable_id'][0]][1]))

[[9.999e-05 9.999e-05 9.999e-05 9.999e-05]
 [0.00990099 0.00990099 0.00990099 0.00990099]
 [0.5 0.5 0.5 0.5]
 [None None None None]
 [None None None None]]


In [8]:
# ErrorBudget class arguments
class_args = {
'input_dir': config['paths']['input'],
'output_dir': config['paths']['output'],
'ref_json_filename': config['json_files']['ref_json'],
'pp_json_filename': config['json_files']['pp_json'],
'contrast_filename': config['input_files']['contrast'],
'target_list': [config['targets'][star]['HIP'] 
               for star in config['targets']],
'luminosity': [config['targets'][star]['luminosity']
               for star in config['targets']],
'eeid': [config['targets'][star]['eeid'] 
               for star in config['targets']],
'eepsr': [config['targets'][star]['eepsr'] 
               for star in config['targets']],
'exo_zodi': [config['targets'][star]['exo_zodi'] 
               for star in config['targets']],
'npoints': 3
}

# ErrorBudget.run_etc method arguments
wfe = np.array(config['wfe'])
sensitivity = np.array(config['sensitivity'])
output_filename_prefix = config['output_filename_prefix']

# Undefined:  wfsc_factor, var_par, *args

In [9]:
error_budget = ebs.ErrorBudget(**class_args)

In [49]:
def initialize(var_id=config['mcmc']['prior_args']
               , pars=config['mcmc']['ini_pars']):
    [print(f"{key}\n{pars[key]}") for key in pars.keys()]
    center = [np.array(pars[key][0][0]) for key in pars.keys()]
    print("\nCENTER")
    print(center)
#     print(center.shape)
    spread = [np.array(pars[key][0][1]) for key in pars.keys()]
    print("\nSPREAD")
    print(spread)
    print(spread.shape)
    ini_positn = []
    for array in center:
        positn = center + np.random.rand(array.shape)
        ini_positn.append(1)
    print(ini_positn)
    

In [50]:
initialize()

wfsc_factor
[[[9.9999e-07, 9.9999e-07, 9.9999e-07, 9.9999e-07], [9.999e-05, 9.999e-05, 9.999e-05, 9.999e-05], [0.00990099, 0.00990099, 0.00990099, 0.00990099], [None, None, None, None], [None, None, None, None]], [[9.9999e-09, 9.9999e-09, 9.9999e-09, 9.9999e-09], [9.999e-07, 9.999e-07, 9.999e-07, 9.999e-07], [9.90099e-05, 9.90099e-05, 9.90099e-05, 9.90099e-05], [None, None, None, None], [None, None, None, None]]]
idark
[[[1e-05], [1e-07]]]

CENTER
[array([9.9999e-07, 9.9999e-07, 9.9999e-07, 9.9999e-07]), array([1.e-05])]

SPREAD
[array([9.999e-05, 9.999e-05, 9.999e-05, 9.999e-05]), array([1.e-07])]


AttributeError: 'list' object has no attribute 'shape'