In [1]:
import os
import time
import numpy as np
import matplotlib.pyplot as plt
import yaml
import json
import astropy.units as u
import EXOSIMS
import EXOSIMS.MissionSim as ems
import ebs.error_budget as eb
import ebs.log_pdf as pdf

In [2]:
ebt = eb.ErrorBudget2()
ebt.initialize_for_exosims()

In [3]:
pos = ebt.initialize_walkers()
[print(f"{po}\n") for po in pos]

[1.00496958e-05 1.00003213e-05 1.00046183e-05 9.99653703e-06
 1.00003925e-05 1.00024593e-03 9.99484918e-04 1.00026752e-03
 9.99795405e-04 9.90460455e-02 9.89821042e-02 9.89985093e-02
 9.90098744e-02 2.71368784e-10 6.78133297e-10 6.34607106e-10
 2.94237435e-10 4.54383677e-10]

[9.97945845e-06 1.00001919e-05 1.00033727e-05 1.00011319e-05
 9.99515015e-06 9.99616890e-04 9.99891119e-04 1.00003653e-03
 9.99452001e-04 9.89792348e-02 9.90138476e-02 9.89903961e-02
 9.89774036e-02 3.86600840e-10 5.74347049e-10 2.84439275e-10
 4.16924059e-10 2.81908600e-10]



[None, None]

In [4]:
# print(ebt.log_prior(pos[0]))

In [5]:
# print(ebt.log_merit(pos[0]))

In [6]:
for po in pos:
#     print(ebt.log_prior(po))
    print(ebt.log_merit(po))
#     print(ebt.log_merit(po))

Updated idark to 1.0049695812072212e-05
Updated wfsc_factor to [[1.00003213e-05 1.00046183e-05 9.99653703e-06 1.00003925e-05]
 [1.00024593e-03 9.99484918e-04 1.00026752e-03 9.99795405e-04]
 [9.90460455e-02 9.89821042e-02 9.89985093e-02 9.90098744e-02]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00]]
Updated contrast to [2.71368784e-10 6.78133297e-10 6.34607106e-10 2.94237435e-10
 4.54383677e-10 1.00000000e-11 1.00000000e-11]
specs:
{'skipSaturationCalcs': True,
 'filterBinaries': False,
 'keepStarCatalog': True,
 'minComp': 0,
 'modules': {'BackgroundSources': ' ',
             'Completeness': ' ',
             'Observatory': ' ',
             'OpticalSystem': 'Nemati',
             'PlanetPhysicalModel': ' ',
             'PlanetPopulation': ' ',
             'PostProcessing': ' ',
             'SimulatedUniverse': ' ',
             'StarCatalog'

/home/pinchen/EXOSIMS-master/EXOSIMS/Prototypes/OpticalSystem.py:1418: UserWarning: core_contrast has smaller OWA than current system value for coronagraph. Updating to match table, but you should check your inputs.
  warnings.warn(


Imported TargetList (prototype) from EXOSIMS.Prototypes.TargetList
Imported HWOMissionStars (implementation) from EXOSIMS.StarCatalog.HWOMissionStars
Loaded data from /home/pinchen/.EXOSIMS/downloads/HWOStarList_20230523183444.pkl
Imported Nemati (implementation) from EXOSIMS.OpticalSystem.Nemati
Imported ZodiacalLight (prototype) from EXOSIMS.Prototypes.ZodiacalLight
Imported PostProcessing (prototype) from EXOSIMS.Prototypes.PostProcessing
Imported BackgroundSources (prototype) from EXOSIMS.Prototypes.BackgroundSources
Imported Completeness (prototype) from EXOSIMS.Prototypes.Completeness
Imported PlanetPopulation (prototype) from EXOSIMS.Prototypes.PlanetPopulation
Imported PlanetPhysicalModel (prototype) from EXOSIMS.Prototypes.PlanetPhysicalModel
Loaded star fluxes values from /home/pinchen/.EXOSIMS/cache/TargetList_HWOMissionStars_nStars_5_mode_305fba0c5e7d27c6e2f3679a361e56ec.star_fluxes
Calculating intCutoff_dMag
intCutoff_dMag values stored in /home/pinchen/.EXOSIMS/cache/Targ

/home/pinchen/EXOSIMS-master/EXOSIMS/MissionSim.py:248: UserWarning: 
Unknown key(s): radDos, Pceff for science instrument CONF_NF_Imager

  warnings.warn(f"\n{out}")
/home/pinchen/EXOSIMS-master/EXOSIMS/MissionSim.py:265: UserWarning: 
The following outspec keywords were not used in any module init:
	  default_vals_extra (Nemati)

  warnings.warn(warnstr)
/home/pinchen/EXOSIMS-master/EXOSIMS/Prototypes/OpticalSystem.py:1418: UserWarning: core_contrast has smaller OWA than current system value for coronagraph. Updating to match table, but you should check your inputs.
  warnings.warn(


Calculating intCutoff_dMag
intCutoff_dMag values stored in /home/pinchen/.EXOSIMS/cache/TargetList_HWOMissionStars_Nemati_ZodiacalLight_vals_45d5705a060d6e01ca00f3ef6634fbb1_mode_305fba0c5e7d27c6e2f3679a361e56ec.intCutoff_dMag
Calculating the integration cutoff time completeness
intCutoff_comp values stored in /home/pinchen/.EXOSIMS/cache/TargetList_HWOMissionStars_Completeness_vals_c02fa09eb39a07c9468b2bef4252125a.intCutoff_comp
No planets were generated. Creating single fake planet.
Imported Observatory (prototype) from EXOSIMS.Prototypes.Observatory
Imported TimeKeeping (prototype) from EXOSIMS.Prototypes.TimeKeeping
OBendTimes is: [36.525] d
Loading cached keepout map file from /home/pinchen/.EXOSIMS/cache/koMap_7e11e80dbc5ae5b0c6e96016d3de71e9.komap
Keepout Map loaded from cache.
coronagraph
Loading cached fZ from /home/pinchen/.EXOSIMS/cache/CompletenessTargetListNematif4ba627a7eabd3ca5a538901257cd1c8_5_coronagraph.starkfZ
Loading cached fZmins from /home/pinchen/.EXOSIMS/cache/C

/home/pinchen/EXOSIMS-master/EXOSIMS/MissionSim.py:248: UserWarning: 
Unknown key(s): radDos, Pceff for science instrument CONF_NF_Imager

  warnings.warn(f"\n{out}")
/home/pinchen/EXOSIMS-master/EXOSIMS/MissionSim.py:265: UserWarning: 
The following outspec keywords were not used in any module init:
	  default_vals_extra (Nemati)

  warnings.warn(warnstr)
