In [1]:
import os
import time
import numpy as np
import yaml
import json
import astropy.units as u
import EXOSIMS
import EXOSIMS.MissionSim as ems
import ebs.error_budget as eb

In [2]:
ebt = eb.ErrorBudget2()

In [3]:
ebt.run_exosims()

Imported SurveySimulation (prototype) from EXOSIMS.Prototypes.SurveySimulation
Numpy random seed is: 730431822
Imported SimulatedUniverse (prototype) from EXOSIMS.Prototypes.SimulatedUniverse


/home/pinchen/EXOSIMS-master/EXOSIMS/Prototypes/OpticalSystem.py:1418: UserWarning: core_contrast has smaller OWA than current system value for coronagraph. Updating to match table, but you should check your inputs.
  warnings.warn(


Imported TargetList (prototype) from EXOSIMS.Prototypes.TargetList
Imported HWOMissionStars (implementation) from EXOSIMS.StarCatalog.HWOMissionStars
Loaded data from /home/pinchen/.EXOSIMS/downloads/HWOStarList_20230523183444.pkl
Imported Nemati (implementation) from EXOSIMS.OpticalSystem.Nemati
Imported ZodiacalLight (prototype) from EXOSIMS.Prototypes.ZodiacalLight
Imported PostProcessing (prototype) from EXOSIMS.Prototypes.PostProcessing
Imported BackgroundSources (prototype) from EXOSIMS.Prototypes.BackgroundSources
Imported Completeness (prototype) from EXOSIMS.Prototypes.Completeness
Imported PlanetPopulation (prototype) from EXOSIMS.Prototypes.PlanetPopulation
Imported PlanetPhysicalModel (prototype) from EXOSIMS.Prototypes.PlanetPhysicalModel
Loaded star fluxes values from /home/pinchen/.EXOSIMS/cache/TargetList_HWOMissionStars_nStars_5_mode_305fba0c5e7d27c6e2f3679a361e56ec.star_fluxes
Calculating intCutoff_dMag
intCutoff_dMag values stored in /home/pinchen/.EXOSIMS/cache/Targ

/home/pinchen/EXOSIMS-master/EXOSIMS/MissionSim.py:250: UserWarning: 
Unknown key(s): radDos, Pceff for science instrument CONF_NF_Imager

  warnings.warn(f"\n{out}")
/home/pinchen/EXOSIMS-master/EXOSIMS/MissionSim.py:267: UserWarning: 
The following outspec keywords were not used in any module init:
	  default_vals_extra (Nemati)

  warnings.warn(warnstr)


In [4]:
print(ebt.int_time)

[[       nan        nan        nan]
 [       nan        nan        nan]
 [       nan        nan        nan]
 [       nan        nan        nan]
 [0.40758613 0.07688503        nan]] d


In [5]:
ebt.initialize_walkers()

MCMC Variable:  wfsc_factor
    keyword:  center
    keyword:  spread
MCMC Variable:  idark
    keyword:  center
    keyword:  spread


In [6]:
ebt.repack_array('wfsc_factor', np.random.rand(3*4))

(array([0.49410686, 0.63808389, 0.88429914, 0.27042586, 0.25180813,
       0.47184169, 0.10976594, 0.74678769, 0.221962  , 0.50932147,
       0.17008699, 0.16766118]),)
[[9.99990e-07 9.99990e-07 9.99990e-07 9.99990e-07]
 [9.99900e-05 9.99900e-05 9.99900e-05 9.99900e-05]
 [9.90099e-03 9.90099e-03 9.90099e-03 9.90099e-03]
 [        nan         nan         nan         nan]
 [        nan         nan         nan         nan]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))
[[1.e-06 1.e-06 1.e-06 1.e-06]
 [1.e-03 1.e-03 1.e-03 1.e-03]
 [5.e-01 5.e-01 5.e-01 5.e-01]
 [1.e+00 1.e+00 1.e+00 1.e+00]
 [1.e+00 1.e+00 1.e+00 1.e+00]
 [1.e+00 1.e+00 1.e+00 1.e+00]]
[[0.49410686 0.63808389 0.88429914 0.27042586]
 [0.25180813 0.47184169 0.10976594 0.74678769]
 [0.221962   0.50932147 0.17008699 0.16766118]
 [1.         1.         1.         1.        ]
 [1.         1.         1.         1.        ]
 [1.         1.         1.         1.        ]]


In [7]:
ebt.wfsc_factor

array([[0.49410686, 0.63808389, 0.88429914, 0.27042586],
       [0.25180813, 0.47184169, 0.10976594, 0.74678769],
       [0.221962  , 0.50932147, 0.17008699, 0.16766118],
       [1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        ]])