In [1]:
import os
import time
import numpy as np
import matplotlib.pyplot as plt
import yaml
import json
import astropy.units as u
from astropy.io import fits
import EXOSIMS
import EXOSIMS.MissionSim as ems
import ebs.error_budget as eb


In [2]:
ebt = eb.ErrorBudget2()
ebt.initialize_for_exosims()

Wrote ppFact FITS file ./inputs/ppFact_5144675304.fits


In [3]:
# t1 = time.time()
# smp = ebt.run_mcmc(parallel=False)
# print(f"elapsed time: {time.time()-t1} s")

In [4]:
# import corner

In [5]:
state = ebt.initialize_walkers()[0]
print(state)

[1.00339203e-05 4.98452244e-07 4.98053630e-03 4.95928727e-07
 5.04226805e-03 5.03022443e-07 4.95617209e-03 5.00340230e-07
 5.04517066e-03 5.02812295e-07 4.99763028e-03 5.02022062e-07
 5.03417319e-03 1.00627846e-10 9.90366266e-11 1.00957193e-10
 9.94598430e-11 1.00095644e-10 1.00122053e-10 1.50098716e-01
 1.49710379e-01 1.49818347e-01 1.49389279e-01 1.49745444e-01
 1.50383119e-01]


In [6]:
ebt.log_merit(state)

ppFact1: [1. 1. 1. 1. 1. 1.]
var_name: idark
arr: 3e-05
use_values: [1.00339203e-05]
var_name: wfsc_factor
arr: [[1.e-06 1.e+00 1.e+00 1.e+00]
 [2.e-04 1.e+00 1.e+00 1.e+00]
 [2.e-03 1.e+00 1.e+00 1.e+00]
 [2.e-01 1.e+00 1.e+00 1.e+00]
 [1.e+00 1.e+00 1.e+00 1.e+00]
 [1.e+00 1.e+00 1.e+00 1.e+00]]
use_values: [4.98452244e-07 4.98053630e-03 4.95928727e-07 5.04226805e-03
 5.03022443e-07 4.95617209e-03 5.00340230e-07 5.04517066e-03
 5.02812295e-07 4.99763028e-03 5.02022062e-07 5.03417319e-03]
ppFact2: [0.01264299 0.03194892 0.03779138 0.03779138 0.01889569 0.01889569]
Wrote ppFact FITS file ./inputs/ppFact_2907101373.fits
var_name: contrast
arr: [1.e-09 2.e-10 1.e-10 1.e-10 1.e-10 1.e-10]
use_values: [1.00627846e-10 9.90366266e-11 1.00957193e-10 9.94598430e-11
 1.00095644e-10 1.00122053e-10]
ppFact2: [0.12564102 0.06451941 0.03743308 0.03799663 0.01887764 0.01887266]
Wrote ppFact FITS file ./inputs/ppFact_6135726251.fits
var_name: throughput
arr: [0.01 0.08 0.15 0.15 0.15 0.08]
use_values

/home/pinchen/EXOSIMS-master/EXOSIMS/Prototypes/OpticalSystem.py:580: UserWarning: Input FoV (9.5 arcsec) is larger than FoV computed from pixelScale (4.75 arcsec) for instrument CONS_NF_Imager. This feels like a mistkae.
  warnings.warn(
/home/pinchen/EXOSIMS-master/EXOSIMS/Prototypes/OpticalSystem.py:1418: UserWarning: core_contrast has smaller OWA than current system value for coronagraph-550. Updating to match table, but you should check your inputs.
  warnings.warn(


Imported TargetList (prototype) from EXOSIMS.Prototypes.TargetList
Imported HWOMissionStars (implementation) from EXOSIMS.StarCatalog.HWOMissionStars
Loaded data from /home/pinchen/.EXOSIMS/downloads/HWOStarList_20230523183444.pkl
Imported Nemati (implementation) from EXOSIMS.OpticalSystem.Nemati
Imported ZodiacalLight (prototype) from EXOSIMS.Prototypes.ZodiacalLight
Imported PostProcessing (prototype) from EXOSIMS.Prototypes.PostProcessing
Imported BackgroundSources (prototype) from EXOSIMS.Prototypes.BackgroundSources
Imported Completeness (prototype) from EXOSIMS.Prototypes.Completeness
Imported PlanetPopulation (prototype) from EXOSIMS.Prototypes.PlanetPopulation
Imported PlanetPhysicalModel (prototype) from EXOSIMS.Prototypes.PlanetPhysicalModel
Star fluxes stored in /home/pinchen/.EXOSIMS/cache/TargetList_HWOMissionStars_nStars_5_mode_825b6da26cb6dfc97b90b4fcb738af0d.star_fluxes
Calculating intCutoff_dMag
intCutoff_dMag values stored in /home/pinchen/.EXOSIMS/cache/TargetList_HW

/home/pinchen/EXOSIMS-master/EXOSIMS/MissionSim.py:265: UserWarning: 
The following outspec keywords were not used in any module init:
	  default_vals_extra (Nemati)

  warnings.warn(warnstr)


0.0

In [7]:
with fits.open('inputs/ppFact_3433275331.fits') as hdu:
    print(hdu[0].data)

[[0.0435     0.12435385]
 [0.061      0.06379724]
 [0.0785     0.03719909]
 [0.0955     0.03751007]
 [0.113      0.01875384]
 [0.1305     0.01876169]]
