In [1]:
import os
import time
import numpy as np
import matplotlib.pyplot as plt
import yaml
import json
import astropy.units as u
import EXOSIMS
import EXOSIMS.MissionSim as ems
import ebs.error_budget as eb
import ebs.log_pdf as pdf

In [2]:
ebt = eb.ErrorBudget2()
ebt.initialize_for_exosims()

In [3]:
pos = ebt.initialize_walkers()
print(pos[0])

[9.99899817e-06 1.00011469e-05 1.00019329e-05 1.00001146e-05
 1.00010344e-05 9.99887422e-04 1.00028174e-03 9.99909135e-04
 1.00021316e-03 9.89756598e-02 9.90023122e-02 9.90421132e-02
 9.89607719e-02 3.94594750e-10 6.17114551e-10 4.31980678e-10
 6.26031704e-10 6.25112955e-10]


In [4]:
print(ebt.log_prior(pos[0]))

1.0


In [5]:
# print(ebt.log_merit(pos[0]))

In [6]:
ebt.log_probability(pos[0])

Updated idark to 9.99899816611006e-06
Updated wfsc_factor to [[1.00011469e-05 1.00019329e-05 1.00001146e-05 1.00010344e-05]
 [9.99887422e-04 1.00028174e-03 9.99909135e-04 1.00021316e-03]
 [9.89756598e-02 9.90023122e-02 9.90421132e-02 9.89607719e-02]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00]]
Updated contrast to [3.94594750e-10 6.17114551e-10 4.31980678e-10 6.26031704e-10
 6.25112955e-10 1.00000000e-11 1.00000000e-11]
Imported SurveySimulation (prototype) from EXOSIMS.Prototypes.SurveySimulation
Numpy random seed is: 901911989
Imported SimulatedUniverse (prototype) from EXOSIMS.Prototypes.SimulatedUniverse


/home/pinchen/EXOSIMS-master/EXOSIMS/Prototypes/OpticalSystem.py:1418: UserWarning: core_contrast has smaller OWA than current system value for coronagraph. Updating to match table, but you should check your inputs.
  warnings.warn(


Imported TargetList (prototype) from EXOSIMS.Prototypes.TargetList
Imported HWOMissionStars (implementation) from EXOSIMS.StarCatalog.HWOMissionStars
Loaded data from /home/pinchen/.EXOSIMS/downloads/HWOStarList_20230523183444.pkl
Imported Nemati (implementation) from EXOSIMS.OpticalSystem.Nemati
Imported ZodiacalLight (prototype) from EXOSIMS.Prototypes.ZodiacalLight
Imported PostProcessing (prototype) from EXOSIMS.Prototypes.PostProcessing
Imported BackgroundSources (prototype) from EXOSIMS.Prototypes.BackgroundSources
Imported Completeness (prototype) from EXOSIMS.Prototypes.Completeness
Imported PlanetPopulation (prototype) from EXOSIMS.Prototypes.PlanetPopulation
Imported PlanetPhysicalModel (prototype) from EXOSIMS.Prototypes.PlanetPhysicalModel
Loaded star fluxes values from /home/pinchen/.EXOSIMS/cache/TargetList_HWOMissionStars_nStars_5_mode_305fba0c5e7d27c6e2f3679a361e56ec.star_fluxes
Calculating intCutoff_dMag
intCutoff_dMag values stored in /home/pinchen/.EXOSIMS/cache/Targ

/home/pinchen/EXOSIMS-master/EXOSIMS/MissionSim.py:250: UserWarning: 
Unknown key(s): radDos, Pceff for science instrument CONF_NF_Imager

  warnings.warn(f"\n{out}")
/home/pinchen/EXOSIMS-master/EXOSIMS/MissionSim.py:267: UserWarning: 
The following outspec keywords were not used in any module init:
	  default_vals_extra (Nemati)

  warnings.warn(warnstr)


1.0