In [1]:
import os
import time
import numpy as np
import astropy.units as u
import EXOSIMS
import EXOSIMS.MissionSim as ems

In [2]:
spec = {
    "ppFact": 0.1,
    "minComp": 0,
    "filterBinaries": False,
    "keepStarCatalog": True,
    "pupilDiam": 6.0,
    "obscurFac": 0.1,
    "modules": {
        "PlanetPopulation": " ",
        "StarCatalog": "HWOMissionStars",
        "OpticalSystem": "Nemati",
        "ZodiacalLight": " ",
        "BackgroundSources": " ",
        "PlanetPhysicalModel": " ",
        "Observatory": " ",
        "TimeKeeping": " ",
        "PostProcessing": " ",
        "Completeness": " ",
        "TargetList": " ",
        "SimulatedUniverse": " ",
        "SurveySimulation": " ",
        "SurveyEnsemble": " "
    },
    "scienceInstruments": [
        {
            "name": "spectro_1",
            "QE": 0.835,
            "optics": 0.66,
            "sread": 1.7e-06,
            "idark": 3e-5,
            "texp": 3,
            "Rs": 1.0,
            "pixelNumber": 1024,
            "pixelSize": 1.3e-05,
            "FoV": 9.5,
            "pixelScale": 0.02,
            "CIC": 2.1e-3,
            "radDos": 0,
            "Pceff": 1.0,
            "ENF": 1.0
        }
    ],
    "starlightSuppressionSystems": [
        {
            "name": "coronagraph",
            "optics": 1.0,
            "lam": 550.0,
            "BW": 0.2,
            "ohTime": 1.0,
            "occulter": False,
            "IWA": 0.055,
            "OWA": 0.5,
            "occ_trans": 0.2,
            "core_thruput": "./inputs/example_throughput.csv",
            "core_area": 5.52e-4,
            "core_contrast": "./inputs/example_contrast.csv"
        }
    ],
    "observingModes": [
        {
            "SNR": 3.0,
            "detectionMode": True,
            "instName": "spectro_1",
            "systName": "coronagraph",
            "timeMultiplier": 1.0
        }
    ]
}

In [3]:
start = time.time()
# sim = ems.MissionSim(os.path.join(EXOSIMS.__path__[0], 'Scripts', 'sampleScript_coron.json'))
sim = ems.MissionSim(**spec)
end = time.time()
timer1 = end - start
start = time.time()
target = "HIP 79672"
sInd = np.array([np.where(sim.TargetList.Name == target)[0][0]])
eeid = 0.07399
eepsr = 1.06e-10
dMag = -2.5*np.log10(eepsr)
mode = sim.OpticalSystem.observingModes[0]
int_time = sim.OpticalSystem.calc_intTime(
    sim.TargetList
    , sInd
    , 1.0*sim.ZodiacalLight.fZ0.unit
    , 3.0*sim.ZodiacalLight.fEZ0.value*sim.ZodiacalLight.fEZ0.unit
    , dMag
    , eeid*u.arcsec
    , mode)
end = time.time()
timer2 = end - start
print(f"Execution time = {(end-start)} s")

Imported SurveySimulation (prototype) from EXOSIMS.Prototypes.SurveySimulation
Numpy random seed is: 662070464
Imported SimulatedUniverse (prototype) from EXOSIMS.Prototypes.SimulatedUniverse
Imported TargetList (prototype) from EXOSIMS.Prototypes.TargetList
Imported HWOMissionStars (implementation) from EXOSIMS.StarCatalog.HWOMissionStars
Loaded data from /home/pinchen/.EXOSIMS/downloads/HWOStarList_20230523183444.pkl
Imported Nemati (implementation) from EXOSIMS.OpticalSystem.Nemati
Imported ZodiacalLight (prototype) from EXOSIMS.Prototypes.ZodiacalLight
Imported PostProcessing (prototype) from EXOSIMS.Prototypes.PostProcessing
Imported BackgroundSources (prototype) from EXOSIMS.Prototypes.BackgroundSources
Imported Completeness (prototype) from EXOSIMS.Prototypes.Completeness
Imported PlanetPopulation (prototype) from EXOSIMS.Prototypes.PlanetPopulation
Imported PlanetPhysicalModel (prototype) from EXOSIMS.Prototypes.PlanetPhysicalModel
Loaded star fluxes values from /home/pinchen/.

/home/pinchen/anaconda3/envs/exosims/lib/python3.11/site-packages/EXOSIMS/MissionSim.py:250: UserWarning: 
Unknown key(s): radDos, Pceff for science instrument spectro_1

  warnings.warn(f"\n{out}")
/home/pinchen/anaconda3/envs/exosims/lib/python3.11/site-packages/EXOSIMS/MissionSim.py:267: UserWarning: 
The following outspec keywords were not used in any module init:
	  default_vals_extra (Nemati)

  warnings.warn(warnstr)


In [4]:
print(f"Execution time = {timer1} s")

Execution time = 1.23167085647583 s


In [5]:
print(f"Execution time = {timer2} s")

Execution time = 0.004787445068359375 s


In [6]:
import ebs.error_budget as eb

In [7]:
t = eb.ErrorBudget2()

In [8]:
t.wfe = np.random.rand(2,3)
t.wfsc_factor = np.random.rand(2,3)
t.sensitivity = np.random.rand(4,3)
t.contrast = np.random.rand(4)
t.angles = np.random.rand(4)

In [9]:
t.delta_contrast

array([8.24928336e-13, 4.50543799e-13, 6.69751674e-13, 7.26637333e-13])

In [10]:
t.ppFact

array([3.43309505e-12, 5.29263047e-13, 1.41072225e-11, 2.26769636e-12])

In [11]:
t.write_ppFact_fits(".")

In [12]:
np.random.rand(4,)

array([0.08588334, 0.30228237, 0.0081056 , 0.37583956])