In [1]:
import os
import numpy as np
from ebs import error_budget as eb

ModuleNotFoundError: No module named 'ebs'

In [2]:
ebo = eb.ErrorBudgetMcmc('../inputs/config_quick.yml')

In [3]:
ebo.config['paths']['input'] = os.path.join('..', 'inputs')

In [4]:
ebo.initialize_for_exosims()

In [5]:
print(ebo.wfsc_factor)

[[5.00e-05 6.67e-05 2.00e-04 2.00e-04]
 [1.15e-02 3.82e-02 1.00e+00 1.00e+00]
 [1.15e-02 3.82e-02 1.00e+00 1.00e+00]
 [1.15e-02 1.92e-01 2.86e-01 1.00e+00]
 [5.71e-02 1.92e-01 2.86e-01 1.00e+00]
 [5.71e-02 1.92e-01 2.86e-01 1.00e+00]]


In [6]:
print(ebo.ppFact)

[0.02908757 0.09955891 0.07345265 0.07345265 0.03672633 0.03672633]


In [7]:
etc = ebo.run_exosims()

idark: 3e-05
Imported SurveySimulation (prototype) from EXOSIMS.Prototypes.SurveySimulation
Numpy random seed is: 842732203
Imported SimulatedUniverse (prototype) from EXOSIMS.Prototypes.SimulatedUniverse
Imported TargetList (prototype) from EXOSIMS.Prototypes.TargetList
Imported HWOMissionStars (implementation) from EXOSIMS.StarCatalog.HWOMissionStars
Loaded data from /home/pinchen/.EXOSIMS/downloads/HWOStarList_20230523183444.pkl
Imported Nemati (implementation) from EXOSIMS.OpticalSystem.Nemati
Imported ZodiacalLight (prototype) from EXOSIMS.Prototypes.ZodiacalLight
Imported PostProcessing (prototype) from EXOSIMS.Prototypes.PostProcessing
Imported BackgroundSources (prototype) from EXOSIMS.Prototypes.BackgroundSources
Imported Completeness (prototype) from EXOSIMS.Prototypes.Completeness
Imported PlanetPopulation (prototype) from EXOSIMS.Prototypes.PlanetPopulation
Imported PlanetPhysicalModel (prototype) from EXOSIMS.Prototypes.PlanetPhysicalModel
Loaded star fluxes values from /h

/home/pinchen/EXOSIMS-master/EXOSIMS/Prototypes/OpticalSystem.py:1418: UserWarning: core_contrast has smaller OWA than current system value for coronagraph-550. Updating to match table, but you should check your inputs.
  warnings.warn(
/home/pinchen/EXOSIMS-master/EXOSIMS/MissionSim.py:265: UserWarning: 
The following outspec keywords were not used in any module init:
	  default_vals_extra (Nemati)

  warnings.warn(warnstr)


In [8]:
print(etc[0])
print(etc[0].mean())
print(1/etc[0].mean())
ebo.clean_files()

[[ 1.43995596  4.09137641 10.27504984]] d
5.2687940684271295 d
0.18979675178280894 1 / d


In [9]:
ebo.wfsc_factor[0, :] = 0.0
print(ebo.wfsc_factor)

[[0.     0.     0.     0.    ]
 [0.0115 0.0382 1.     1.    ]
 [0.0115 0.0382 1.     1.    ]
 [0.0115 0.192  0.286  1.    ]
 [0.0571 0.192  0.286  1.    ]
 [0.0571 0.192  0.286  1.    ]]


In [10]:
print(ebo.ppFact)

[0.02655234 0.09089748 0.06704023 0.06704023 0.03352011 0.03352011]


In [11]:
ebo.write_ppFact_fits()
ebo.exosims_pars_dict['ppFact'] = ebo.ppFact_filename

In [12]:
etc = ebo.run_exosims()

idark: 3e-05
Imported SurveySimulation (prototype) from EXOSIMS.Prototypes.SurveySimulation
Numpy random seed is: 328629948
Imported SimulatedUniverse (prototype) from EXOSIMS.Prototypes.SimulatedUniverse
Imported TargetList (prototype) from EXOSIMS.Prototypes.TargetList
Imported HWOMissionStars (implementation) from EXOSIMS.StarCatalog.HWOMissionStars
Loaded data from /home/pinchen/.EXOSIMS/downloads/HWOStarList_20230523183444.pkl
Imported Nemati (implementation) from EXOSIMS.OpticalSystem.Nemati
Imported ZodiacalLight (prototype) from EXOSIMS.Prototypes.ZodiacalLight
Imported PostProcessing (prototype) from EXOSIMS.Prototypes.PostProcessing
Imported BackgroundSources (prototype) from EXOSIMS.Prototypes.BackgroundSources
Imported Completeness (prototype) from EXOSIMS.Prototypes.Completeness
Imported PlanetPopulation (prototype) from EXOSIMS.Prototypes.PlanetPopulation
Imported PlanetPhysicalModel (prototype) from EXOSIMS.Prototypes.PlanetPhysicalModel
Loaded star fluxes values from /h

/home/pinchen/EXOSIMS-master/EXOSIMS/Prototypes/OpticalSystem.py:1418: UserWarning: core_contrast has smaller OWA than current system value for coronagraph-550. Updating to match table, but you should check your inputs.
  warnings.warn(
/home/pinchen/EXOSIMS-master/EXOSIMS/MissionSim.py:265: UserWarning: 
The following outspec keywords were not used in any module init:
	  default_vals_extra (Nemati)

  warnings.warn(warnstr)


In [13]:
print(etc[0])
print(etc[0].mean())
print(1/etc[0].mean())
ebo.clean_files()

[[1.26487113 3.45045867 9.95386675]] d
4.889732184394616 d
0.2045101781221188 1 / d
